[exp]
#exp_name='AC_8_nodes'
num_trials = 2
buffer_size = [0.1, 0.2]
num_layers = 3
num_layer_nodes_max = 2
run_ddp = false
coalition_influence_aggregator = 'sum'
makespan_constraint = 0.8

from_file = true
filename = 'autonomous_construction/experiments_examples/8nodes_2.toml'
