[exp]
exp_name = 'tasks_15_exp'
num_trials = 5
num_layers = 6
num_robots = 4
num_layer_nodes_max = 4
num_nodes = 15
run_ddp = false
coalition_influence_aggregator = 'mix'
makespan_constraint = 0.6
topology_handle = 'generate_graph_topology_c'
edge_probability = 0.4


from_file = false
filename = ''
