[exp]

max_steps = 0
edges = [[0,1], [1,2], [1,3], [3, 4],[2, 4]]
num_tasks = 5

numrobots = 4
coalition_types = ["polynomial", "polynomial", "polynomial", "polynomial", "polynomial"] # polynomial function is param[0] + param[1]*x + param[2]*x^2 ....
coalition_params = [[0, 0, 0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0], [0.0, 1.0, 1.0]]

dependency_types = ["polynomial", "polynomial", "polynomial", "polynomial",  "polynomial"]
dependency_params = [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]

aggs = ["or", "or", "or", "or", "or"] #aggregation functions for the influence function agg

[ddp]
constraint_type='qp' #'qp' or 'None'
constraint_buffer='soft' # 'None' or 'soft' or 'hard'
alpha_anneal='True' #'True' or 'False'
flow_lookahead='False' #'True' or 'False'
