[exp]

max_steps = 0
edges = [[0,1], [1,2], [2,3]]
num_tasks = 4

numrobots = 4
coalition_types = ["null", "sigmoid", "sigmoid", "sigmoid"]
coalition_params = [[0.0, 0.0, 0.0], [1.0, 10.0, 0.5], [1.0, 10.0, 0.5], [1.0, 10.0, 0.5]]

dependency_types = ["sigmoid", "sigmoid", "sigmoid"]
dependency_params = [[1.0, 10.0, 0.5], [1.0, 10.0, 0.5], [1.0, 10.0, 0.5]]

aggs = ["or", "or", "or", "or"] #aggregation functions for the influence function agg

[ddp]
constraint_type='qp' #'qp' or 'None'
