[exp]
exp_name = 'tasks_20_makespan_10_exp'
num_trials = 10
num_layers = 7
num_robots = 4
num_layer_nodes_max = 4
num_nodes = 20
run_ddp = false
coalition_influence_aggregator = 'mix'
makespan_constraint = 1.0


from_file = false
filename = ''
