[exp]
exp_name = 'tasks_16_makespan_75_exp'
num_trials = 5
num_layers = 6
num_robots = 4
num_layer_nodes_max = 4
num_nodes = 16
run_ddp = false
coalition_influence_aggregator = 'mix'
makespan_constraint = 0.75


from_file = false
filename = ''
