[exp]
exp_name = 'tasks_12_makespan_50_exp'
num_trials = 10
num_layers = 5
num_robots = 4
num_layer_nodes_max = 3
num_nodes = 12
run_ddp = false
coalition_influence_aggregator = 'mix'
makespan_constraint = 0.5


from_file = false
filename = ''
