[exp]
exp_name = 'tasks_30_exp'
num_trials = 10
num_layers = 11
num_robots = 4
num_layer_nodes_max = 4
num_nodes = 30
run_ddp = false
run_minlp = false
coalition_influence_aggregator = 'mix'
makespan_constraint = 0.6


from_file = false
filename = ''
