[exp]
exp_name = 'tasks_25_exp'
num_trials = 5
num_layers = 9
num_robots = 4
num_layer_nodes_max = 4
num_nodes = 25
run_ddp = false
coalition_influence_aggregator = 'mix'
makespan_constraint = 0.6


from_file = false
filename = ''
