[exp]
exp_name = 'tasks_08_makespan_10_exp'
num_trials = 10
num_layers = 4
num_robots = 4
num_layer_nodes_max = 3
num_nodes = 8
run_ddp = false
coalition_influence_aggregator = 'mix'
makespan_constraint = 1.0


from_file = false
filename = ''
