[exp]
exp_name = 'tasks_06_exp'
num_trials = 5
num_layers = 2
num_robots = 2
num_layer_nodes_max = 5
num_nodes = 6
run_ddp = false
coalition_influence_aggregator = 'sum'
makespan_constraint = 0.6


from_file = false
filename = ''
