[exp]
exp_name = 'tasks_35_exp'
num_trials = 5
num_layers = 12
num_robots = 4
num_layer_nodes_max = 5
num_nodes = 40
run_ddp = false
run_minlp = false
coalition_influence_aggregator = 'mix'
makespan_constraint = 0.6


from_file = false
filename = ''
