[exp]
exp_name = 'tasks_08_exp'
num_trials = 5
num_layers = 4
num_robots = 2
num_layer_nodes_max = 3
num_nodes = 8
run_ddp = false
coalition_influence_aggregator = 'sum'
makespan_constraint = 0.6


from_file = false
filename = ''
