[exp]

edges = [[0,1], [1,2], [2,3]]
num_tasks = 4

numrobots = 4
coalition_types = ["null", "sigmoid", "sigmoid", "sigmoid"]
coalition_params = [[0, 0, 0], [1.0, 1.0, 1.5], [1.0, 6.0, 1.5], [1, 0, 0]]

dependency_types = ["null", "sigmoid", "sigmoid"]
dependency_params = [[0, 0, 0], [1.0, 3.0, 1.0], [1.0, 3.0, 1.0]]

aggs = ["and", "and", "and", "and"] #aggregation functions for the influence function agg

[ddp]
constraint_type='None' #'qp' or 'None'
