[exp]

edges = [[0,1], [1,2], [2,3]]
num_tasks = 4

numrobots = 4
coalition_types = ["null", "sigmoid", "sigmoid", "sigmoid"]
coalition_params = [[0.0, 0.0, 0.0], [0.0, 1.0, 1.5], [0.0, 1.0, 1.5], [1.0, 1.0, 1.5]]

dependency_types = ["null", "sigmoid", "sigmoid"]
dependency_params = [[0, 0, 0], [0.0, 1.0, 1.5], [1.0, 0.0, 1.5]]

aggs = ["and", "and", "and", "or"] #aggregation functions for the influence function agg

[ddp]
constraint_type='qp' #'qp' or 'None'
