[exp]

edges = [[0,1], [1,2], [1,3], [2,4], [3,4]]
num_tasks = 5

numrobots = 4
coalition_types = ["sigmoid", "sigmoid", "sigmoid", "sigmoid", "sigmoid"]
coalition_params = [[1, 0, 0], [10.0, 6.0, 1.5], [10.0, 6.0, 1.5], [10.0, 6.0, 1.5], [1, 0, 0]]

dependency_types = ["sigmoid", "sigmoid", "sigmoid", "sigmoid", "sigmoid"]
dependency_params = [[1.0, 6.0, 2.0], [1.0, 6.0, 2.0], [1.0, 6.0, 100.0], [1.0, 6.0, 2.0], [1.0, 6.0, 2.0]]

aggs = ["m", "m", "m", "m", "m"] #aggregation functions for the influence function agg
