[exp]
numnodes = 5
edges = [[0,1], [1,2], [1,3], [2,4], [3,4]]
rhos = [[1, 0, 0], [10.0, 100.0, 2.5], [10.0, 100.0, 0.5], [1, 0, 0]]
rhotypes = ["d", "s", "s", "d"]
deltas = [[1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0]]
deltatypes = ["d", "d", "d", "d", "d"]
aggs = ["a", "a", "a", "a"]
numrobots = 4