[exp]
scenario="test"
edges = [[0,1], [1,2], [1,3], [2,4], [3,4]]
num_tasks = 5

numrobots = 4
coalition_types = ["null", "sigmoid", "sigmoid", "sigmoid", "null"]
coalition_params = [[0, 0, 0], [1.0, 4.0, 0.6], [1.0, 4.0, 0.6], [1.0, 4.0, 0.6], [0, 0, 0]]

dependency_types = ["null", "sigmoid", "sigmoid", "sigmoid", "sigmoid"]
dependency_params = [[0, 0, 0], [1.0, 3.0, 0.2], [1.0, 3.0, 0.2], [1.0, 3.0, 0.2], [1.0, 3.0, 0.2]]

aggs = ["and", "and", "and", "and", "and"] #aggregation functions for the influence function agg
