[exp]
max_steps = 100
edges = [ [ 0, 1,], [ 0, 2,], [ 1, 3,], [ 2, 3,], [ 3, 4,], [ 4, 5,],]
num_tasks = 6
numrobots = 4
coalition_types = [ "null", "sigmoid", "sigmoid", "sigmoid", "sigmoid", "polynomial",]
coalition_params = [ [ 0, 0, 0,], [ 37.0, 10.0, 0.37,], [ 63.0, 10.0, 0.63,], [ 31.175925925925924, 10.0, 0.31175925925925924,], [ 36.666666666666664, 10.0, 0.36666666666666664,], [ 0.0, 1.0, 0.0,],]
dependency_types = [ "polynomial", "polynomial", "polynomial", "polynomial", "polynomial", "polynomial",]
dependency_params = [ [ 0.0, 0.0, 0.0,], [ 0.0, 0.0, 0.0,], [ 0.0, 0.0, 0.0,], [ 0.0, 0.0, 0.0,], [ 0.0, 0.0, 0.0,], [ 0.0, 0.0, 0.0,],]
aggs = [ "or", "or", "or", "or", "or", "or",]

[ddp]
constraint_type = "qp"

[tower]
heights = [ 72, 37, 66,]
blocks = [ [ [ 0, 111, 111,], [ 111, 300, 189,],], [ [ 0, 182, 182,],], [ [ 0, 120, 120,],],]
