[exp]
max_steps = 100
edges = [ [ 0, 1,], [ 0, 2,], [ 1, 3,], [ 1, 4,], [ 2, 3,], [ 2, 4,], [ 3, 5,], [ 4, 5,], [ 5, 6,],]
num_tasks = 7
numrobots = 4
coalition_types = [ "null", "sigmoid", "sigmoid", "sigmoid", "sigmoid", "sigmoid", "polynomial",]
coalition_params = [ [ 0, 0, 0,], [ 31.0, 10.0, 0.31,], [ 69.0, 10.0, 0.69,], [ 9.333333333333334, 10.0, 0.09333333333333334,], [ 19.333333333333332, 10.0, 0.19333333333333333,], [ 36.38148148148148, 10.0, 0.3638148148148148,], [ 0.0, 1.0, 0.0,],]
dependency_types = [ "polynomial", "polynomial", "polynomial", "polynomial", "polynomial", "polynomial", "polynomial", "polynomial", "polynomial",]
dependency_params = [ [ 0.0, 0.0, 0.0,], [ 0.0, 0.0, 0.0,], [ 0.0, 0.0, 0.0,], [ 0.0, 0.0, 0.0,], [ 0.0, 0.0, 0.0,], [ 0.0, 0.0, 0.0,], [ 0.0, 0.0, 0.0,], [ 0.0, 0.0, 0.0,], [ 0.0, 0.0, 0.0,],]
aggs = [ "or", "or", "or", "or", "or", "or", "or",]

[ddp]
constraint_type = "qp"

[tower]
heights = [ 90, 30, 47,]
blocks = [ [ [ 0, 93, 93,], [ 93, 300, 207,],], [ [ 0, 84, 84,], [ 84, 258, 174,],], [ [ 0, 209, 209,],],]
