[exp]
exp_name = 'makespan_10_exp'
num_trials = 5
num_layers = 5
num_robots = 4
num_layer_nodes_max = 3
run_ddp = false
coalition_influence_aggregator = 'mix'
makespan_constraint = 1.0


from_file = false
filename = ''
