[exp]
exp_name = 'makespan_06_exp'
num_trials = 5
num_layers = 4
num_robots = 2
num_layer_nodes_max = 2
run_ddp = false
coalition_influence_aggregator = 'sum'
makespan_constraint = 0.6


from_file = false
filename = ''
